version: '3'
services:
    webserver:
        build:
            context: ./NGINX
            dockerfile: Dockerfile
        ports:
         - "80:80"
        environment:
         - NGINX_PORT=80
        container_name: webserver
        hostname: webserver
        depends_on:
            - api
            - redis
        networks:
            - network-web
    api:
        build:
          context: ./API
          dockerfile: Dockerfile
        environment:
            - DB_HOST=pgsql
            - DB_PORT=5432
            - DB_NAME=database
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - REDIS_HOST=redis
        depends_on:
            - pgsql
            - redis
        networks:
            - network-web
            - network-database

    pgsql:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: database
            PGDATA: /tmp
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - network-database
    
    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        hostname: redis
        networks:
            - network-database
        ports:
            - "6379:6379"

networks:
  network-database:
  network-web: