version: 2.1
executors:
  lebourreau:
    environment:
      PROJECT_NAME: projet1-team-10
    docker:
      - image: circleci/buildpack-deps:stretch


jobs:
  build:
    executor: lebourreau
    steps:
      - checkout
      - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: Build Docker image
          command: docker-compose -f docker-compose.yml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: test
          command: echo 'Hello there' && echo 'General Kenobi, you are a bold one'
      - run:
          name: Save nodejs Docker image
          command: docker save -o ./api.tar api
      - run:
          name: Tag docker image
          command: docker tag api florianarmenoult/team1-projet-10:latest
      - run:
          name: Publish Node Image to Docker Hub
          command: |
           echo $DOCKER_PASSWORD | base64 --decode | docker login -u $DOCKER_USER --password-stdin
           docker push florianarmenoult/team1-projet-10:latest