version: 2.1
executors:
  lebourreau:
    environment:
      PROJECT_NAME: projet1-team-10
    docker:
      - image: circleci/buildpack-deps:stretch


jobs:
  build:
    executor: lebourreau
    steps:
      - checkout
      - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: Build Docker image
          command: docker-compose -f docker-compose.yml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: Test
          command: echo 'Hello there' && echo 'General Kenobi, you are a bold one'
      - run:
          name: Tag docker image
          command: docker tag project_api florianarmenoult/projet1-team-10:latest
      - run:
          name: List images
          command: docker images -a
      - run:
          name: Save nodejs Docker image
          command: docker save -o ./projet1-team-10_api.tar project_api
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar

  upload-latest:
    executor: lebourreau
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load saved nodejs image
          command: docker load -i /tmp/workspace/projet1-team-10_api.tar
      - run:
          name: View docker images
          command: docker images -a
      - run:
          name: Rename nodejs image
          command: docker tag projet1-team-10 florianarmenoult/projet1-team-10:latest
      - run:
          name: Publish Node Image to Docker Hub
          command: |
           echo $DOCKER_PASSWORD | base64 --decode | docker login -u $DOCKER_USER --password-stdin
           docker push florianarmenoult/projet1-team-10:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - upload-latest:
          requires:
            - build
          filters:
            branches:
              only: master