version: 2.1
executors:
  lebourreau:
    environment:
      PROJECT_NAME: projet1-team-10
    docker:
      - image: circleci/buildpack-deps:stretch


jobs:
  build:
    executor: lebourreau
    steps:
      # - checkout
      # - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: Build Docker image
          command: docker-compose -f docker-compose.yml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: Save nodejs Docker image
          command: docker save -o ./projet1-team-10.tar projet1-team-10